export const REQUEST_HELLO_WORLD = 'REQUEST_HELLO_WORLD';
export const RECEIVE_HELLO_WORLD = 'RECEIVE_HELLO_WORLD';

export const REQUEST_SWANSON_QUOTE = 'REQUEST_SWANSON_QUOTE';
export const RECEIVE_SWANSON_QUOTE = 'RECEIVE_SWANSON_QUOTE';
